In [1]:
import pandas as pd
import pathlib
import numpy as np

In [2]:
train_path = pathlib.Path("/home/starke88/data/haicu/covid_data_challenge_2021/trainSet.txt")
df_train = pd.read_csv(train_path)
df_train

PatientID    ImageFile Hospital        Age  Sex  Temp_C  Cough  \
0       P_131    P_131.png        D  35.913889    0    39.3    1.0   
1       P_132    P_132.png        D  57.266667    0    37.0    0.0   
2       P_195    P_195.png        D  79.263889    0    37.8    1.0   
3       P_193    P_193.png        D  82.000000    0    38.0    1.0   
4       P_140    P_140.png        D  60.791667    1    37.0    1.0   
..        ...          ...      ...        ...  ...     ...    ...   
858    P_1_12   P_1_12.png        F  51.000000    0     NaN    0.0   
859     P_1_8    P_1_8.png        F  57.000000    0     NaN    1.0   
860    P_1_10   P_1_10.png        F  38.000000    0     NaN    0.0   
861    P_1_26   P_1_26.png        F  92.000000    1    38.0    0.0   
862   P_1_146  P_1_146.png        F  80.000000    0    38.4    0.0   

     DifficultyInBreathing    WBC     CRP  Fibrinogen    LDH  Ddimer  \
0                      0.0   5.76   43.40       651.0  387.0   157.0   
1                      0.0  11.48   64.00       700.0  338.0   601.0   
2                      0.0   6.21  115.30       698.0  356.0   448.0   
3                      0.0   7.28  149.30       513.0  482.0     NaN   
4                      0.0   6.37   20.70         NaN    NaN   210.0   
..                     ...    ...     ...         ...    ...     ...   
858                    1.0  14.30   22.79       550.0  368.0  5027.0   
859                    0.0   5.10    8.93       757.0  451.0     NaN   
860                    1.0   7.30    0.23         NaN    NaN  1073.0   
861                    1.0  13.50    3.77       533.0  358.0  2154.0   
862                    0.0   6.70    0.02         NaN  149.0     NaN   

     Ox_percentage  PaO2  SaO2    pH  CardiovascularDisease  \
0             94.0   NaN   NaN   NaN                    0.0   
1             94.0  75.0  96.9  7.42                    0.0   
2             94.0  63.0  94.6  7.39                    1.0   
3             97.0  68.0  96.3  7.46                    0.0   
4             93.0   NaN  97.3   NaN                    0.0   
..             ...   ...   ...   ...                    ...   
858            NaN   NaN   NaN   NaN                    0.0   
859            NaN   NaN   NaN   NaN                    0.0   
860            NaN   NaN   NaN   NaN                    0.0   
861            NaN  75.7   NaN  7.36                    0.0   
862            NaN  80.0   NaN  7.46                    1.0   

     RespiratoryFailure Prognosis  
0                   NaN      MILD  
1                   NaN      MILD  
2                   NaN    SEVERE  
3                   NaN    SEVERE  
4                   NaN      MILD  
..                  ...       ...  
858                 0.0    SEVERE  
859                 0.0    SEVERE  
860                 0.0      MILD  
861                 0.0    SEVERE  
862                 0.0      MILD  

[863 rows x 20 columns]

In [3]:
df_train.dropna().shape

(6, 20)

In [4]:
for c in df_train.columns:
    print(c, "\t\t\t", df_train[c].isna().sum(), "/", len(df_train))

PatientID 			 0 / 863
ImageFile 			 0 / 863
Hospital 			 0 / 863
Age 			 1 / 863
Sex 			 0 / 863
Temp_C 			 154 / 863
Cough 			 5 / 863
DifficultyInBreathing 			 4 / 863
WBC 			 9 / 863
CRP 			 33 / 863
Fibrinogen 			 591 / 863
LDH 			 136 / 863
Ddimer 			 621 / 863
Ox_percentage 			 243 / 863
PaO2 			 170 / 863
SaO2 			 583 / 863
pH 			 207 / 863
CardiovascularDisease 			 19 / 863
RespiratoryFailure 			 159 / 863
Prognosis 			 0 / 863


In [5]:
label_col = "Prognosis"
discard = ["SaO2", "Ddimer", "Fibrinogen"]

df_reduced = df_train.drop(discard, axis=1)
df_reduced

PatientID    ImageFile Hospital        Age  Sex  Temp_C  Cough  \
0       P_131    P_131.png        D  35.913889    0    39.3    1.0   
1       P_132    P_132.png        D  57.266667    0    37.0    0.0   
2       P_195    P_195.png        D  79.263889    0    37.8    1.0   
3       P_193    P_193.png        D  82.000000    0    38.0    1.0   
4       P_140    P_140.png        D  60.791667    1    37.0    1.0   
..        ...          ...      ...        ...  ...     ...    ...   
858    P_1_12   P_1_12.png        F  51.000000    0     NaN    0.0   
859     P_1_8    P_1_8.png        F  57.000000    0     NaN    1.0   
860    P_1_10   P_1_10.png        F  38.000000    0     NaN    0.0   
861    P_1_26   P_1_26.png        F  92.000000    1    38.0    0.0   
862   P_1_146  P_1_146.png        F  80.000000    0    38.4    0.0   

     DifficultyInBreathing    WBC     CRP    LDH  Ox_percentage  PaO2    pH  \
0                      0.0   5.76   43.40  387.0           94.0   NaN   NaN   
1                      0.0  11.48   64.00  338.0           94.0  75.0  7.42   
2                      0.0   6.21  115.30  356.0           94.0  63.0  7.39   
3                      0.0   7.28  149.30  482.0           97.0  68.0  7.46   
4                      0.0   6.37   20.70    NaN           93.0   NaN   NaN   
..                     ...    ...     ...    ...            ...   ...   ...   
858                    1.0  14.30   22.79  368.0            NaN   NaN   NaN   
859                    0.0   5.10    8.93  451.0            NaN   NaN   NaN   
860                    1.0   7.30    0.23    NaN            NaN   NaN   NaN   
861                    1.0  13.50    3.77  358.0            NaN  75.7  7.36   
862                    0.0   6.70    0.02  149.0            NaN  80.0  7.46   

     CardiovascularDisease  RespiratoryFailure Prognosis  
0                      0.0                 NaN      MILD  
1                      0.0                 NaN      MILD  
2                      1.0                 NaN    SEVERE  
3                      0.0                 NaN    SEVERE  
4                      0.0                 NaN      MILD  
..                     ...                 ...       ...  
858                    0.0                 0.0    SEVERE  
859                    0.0                 0.0    SEVERE  
860                    0.0                 0.0      MILD  
861                    0.0                 0.0    SEVERE  
862                    1.0                 0.0      MILD  

[863 rows x 17 columns]

In [6]:
df_reduced = df_reduced.dropna()

In [7]:
df_reduced.describe()

Age         Sex      Temp_C       Cough  DifficultyInBreathing  \
count  314.000000  314.000000  314.000000  314.000000             314.000000   
mean    65.490446    0.328025   37.463694    0.512739               0.487261   
std     14.341841    0.470244    0.968029    0.500636               0.500636   
min     27.000000    0.000000   35.500000    0.000000               0.000000   
25%     56.000000    0.000000   36.700000    0.000000               0.000000   
50%     66.000000    0.000000   37.500000    1.000000               0.000000   
75%     78.000000    1.000000   38.100000    1.000000               1.000000   
max     96.000000    1.000000   40.000000    1.000000               1.000000   

              WBC         CRP          LDH  Ox_percentage        PaO2  \
count  314.000000  314.000000   314.000000     314.000000  314.000000   
mean     6.971401   24.180350   376.792994      92.526115   74.498408   
std      3.422245   37.611437   248.504032       7.463317   28.082467   
min      0.200000    0.010000   115.000000      50.000000   23.000000   
25%      4.700000    4.662500   248.250000      91.000000   60.050000   
50%      6.330000   12.855000   313.500000      95.000000   70.550000   
75%      8.400000   24.797500   428.000000      97.000000   80.900000   
max     26.500000  356.000000  2578.000000     100.000000  285.000000   

               pH  CardiovascularDisease  RespiratoryFailure  
count  314.000000             314.000000          314.000000  
mean     7.451662               0.324841            0.009554  
std      0.051937               0.469063            0.097432  
min      7.048000               0.000000            0.000000  
25%      7.430000               0.000000            0.000000  
50%      7.450000               0.000000            0.000000  
75%      7.480000               1.000000            0.000000  
max      7.620000               1.000000            1.000000

In [8]:
y = df_reduced[["PatientID", label_col]]
y = y.set_index("PatientID")

X_df = df_reduced[[c for c in df_reduced.columns if c not in [label_col, "ImageFile"]]]
X_df = X_df.set_index("PatientID")
X_df

Hospital   Age  Sex  Temp_C  Cough  DifficultyInBreathing    WBC  \
PatientID                                                                    
P_302            E  56.0    0    38.3    0.0                    1.0   7.85   
P_301            E  61.0    0    38.0    1.0                    1.0   3.57   
P_268            E  64.0    0    36.0    1.0                    0.0   5.26   
P_282            E  54.0    0    36.6    1.0                    0.0   7.01   
P_300            E  44.0    0    37.7    0.0                    0.0   9.18   
...            ...   ...  ...     ...    ...                    ...    ...   
P_1_59           F  47.0    1    36.0    1.0                    1.0  11.20   
P_1_73           F  59.0    1    36.3    0.0                    0.0   6.90   
P_1_76           F  52.0    0    37.5    0.0                    1.0   5.40   
P_1_25           F  48.0    0    36.5    0.0                    0.0   5.91   
P_1_134          F  50.0    0    39.0    1.0                    0.0   6.90   

             CRP    LDH  Ox_percentage  PaO2    pH  CardiovascularDisease  \
PatientID                                                                   
P_302       9.00  159.0           93.0  73.2  7.47                    0.0   
P_301      57.40  309.0           92.0  57.0  7.47                    0.0   
P_268      41.90  299.0           96.0  72.2  7.51                    1.0   
P_282      67.90  458.0           97.0  61.0  7.45                    0.0   
P_300      42.70  243.0           98.0  23.0  7.43                    0.0   
...          ...    ...            ...   ...   ...                    ...   
P_1_59      0.02  161.0           97.0  99.0  7.40                    0.0   
P_1_73      1.15  237.0           95.0  82.0  7.39                    0.0   
P_1_76      1.63  307.0           89.0  62.3  7.46                    0.0   
P_1_25      1.86  235.0           99.0  81.9  7.42                    0.0   
P_1_134    22.01  332.0           90.0  81.0  7.44                    0.0   

           RespiratoryFailure  
PatientID                      
P_302                     0.0  
P_301                     0.0  
P_268                     0.0  
P_282                     0.0  
P_300                     0.0  
...                       ...  
P_1_59                    0.0  
P_1_73                    0.0  
P_1_76                    0.0  
P_1_25                    0.0  
P_1_134                   0.0  

[314 rows x 14 columns]

In [9]:
X_df["Hospital"].value_counts()

F    232
E     52
B     30
Name: Hospital, dtype: int64

In [10]:
foo = pd.get_dummies(X_df["Hospital"], prefix="Hospital")
X_df = pd.concat([X_df, foo], axis=1)
X_df = X_df.drop(["Hospital"], axis=1)
X_df

Age  Sex  Temp_C  Cough  DifficultyInBreathing    WBC    CRP  \
PatientID                                                                  
P_302      56.0    0    38.3    0.0                    1.0   7.85   9.00   
P_301      61.0    0    38.0    1.0                    1.0   3.57  57.40   
P_268      64.0    0    36.0    1.0                    0.0   5.26  41.90   
P_282      54.0    0    36.6    1.0                    0.0   7.01  67.90   
P_300      44.0    0    37.7    0.0                    0.0   9.18  42.70   
...         ...  ...     ...    ...                    ...    ...    ...   
P_1_59     47.0    1    36.0    1.0                    1.0  11.20   0.02   
P_1_73     59.0    1    36.3    0.0                    0.0   6.90   1.15   
P_1_76     52.0    0    37.5    0.0                    1.0   5.40   1.63   
P_1_25     48.0    0    36.5    0.0                    0.0   5.91   1.86   
P_1_134    50.0    0    39.0    1.0                    0.0   6.90  22.01   

             LDH  Ox_percentage  PaO2    pH  CardiovascularDisease  \
PatientID                                                            
P_302      159.0           93.0  73.2  7.47                    0.0   
P_301      309.0           92.0  57.0  7.47                    0.0   
P_268      299.0           96.0  72.2  7.51                    1.0   
P_282      458.0           97.0  61.0  7.45                    0.0   
P_300      243.0           98.0  23.0  7.43                    0.0   
...          ...            ...   ...   ...                    ...   
P_1_59     161.0           97.0  99.0  7.40                    0.0   
P_1_73     237.0           95.0  82.0  7.39                    0.0   
P_1_76     307.0           89.0  62.3  7.46                    0.0   
P_1_25     235.0           99.0  81.9  7.42                    0.0   
P_1_134    332.0           90.0  81.0  7.44                    0.0   

           RespiratoryFailure  Hospital_B  Hospital_E  Hospital_F  
PatientID                                                          
P_302                     0.0           0           1           0  
P_301                     0.0           0           1           0  
P_268                     0.0           0           1           0  
P_282                     0.0           0           1           0  
P_300                     0.0           0           1           0  
...                       ...         ...         ...         ...  
P_1_59                    0.0           0           0           1  
P_1_73                    0.0           0           0           1  
P_1_76                    0.0           0           0           1  
P_1_25                    0.0           0           0           1  
P_1_134                   0.0           0           0           1  

[314 rows x 16 columns]

In [11]:
numeric_features = ["Age", "Temp_C", "WBC", "CRP", "LDH", "Ox_percentage", "PaO2", "pH"]
binary_features = [c for c in X_df.columns if c not in numeric_features]

features = numeric_features + binary_features

In [12]:
# 1 -> severe
# 0 -> mild
y["Prognosis"] = (y["Prognosis"] == "SEVERE").astype(np.uint8)
y

Prognosis
PatientID           
P_302              1
P_301              1
P_268              0
P_282              1
P_300              0
...              ...
P_1_59             0
P_1_73             0
P_1_76             1
P_1_25             0
P_1_134            0

[314 rows x 1 columns]

In [13]:
y.value_counts()

Prognosis
0            164
1            150
dtype: int64

In [14]:
assert len(X_df) == len(y)

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [16]:
train, valid = train_test_split(X_df.index.to_numpy(), test_size=.25, stratify=y[label_col], random_state=52)
print(len(train), len(valid))

235 79


In [17]:
train[:4]

array(['P_364', 'P_499', 'P_429', 'P_1_119'], dtype=object)

In [52]:
picked_features = X_df.columns

picked_features = [
    "LDH",
    "Age",
    "PaO2",
    "CRP",
    "WBC",
    "pH"
]


X = X_df[picked_features]

In [53]:
mask_train = X.index.isin(train)
feat_names = X.columns

X_train = X[mask_train]
y_train = y[mask_train]

X_valid = X[~mask_train]
y_valid = y[~mask_train]

print(X_train.shape, y_train.shape)
print(X_valid.shape, y_valid.shape)

(235, 6) (235, 1)
(79, 6) (79, 1)


In [54]:
X_train.dtypes

LDH     float64
Age     float64
PaO2    float64
CRP     float64
WBC     float64
pH      float64
dtype: object

In [55]:
scaler = MinMaxScaler()
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train.to_numpy())
y_train = y_train.to_numpy().squeeze()

X_valid = scaler.transform(X_valid.to_numpy())
y_valid = y_valid.to_numpy().squeeze()

In [56]:
print(X_train.shape, y_train.shape)
print(X_valid.shape, y_valid.shape)

(235, 6) (235,)
(79, 6) (79,)


In [57]:
## simple logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, roc_curve, confusion_matrix

model = RandomForestClassifier() 
#model = LogisticRegression(penalty="l1", solver="liblinear")

model.fit(X_train, y_train)
if hasattr(model, "coef_"):
    coeffs = dict(zip(feat_names, model.coef_[0]))
    print(coeffs)
    print("\nsignificant coeffs", {k:v for k,v in coeffs.items() if np.abs(v) > .01})
print()

def evaluate_model(model, X, y):
    pred_y = model.predict(X)

    print("-Classification metrics\n", classification_report(y, pred_y))
    print()
    print("-Confusion matrix\n", confusion_matrix(y, pred_y))
    print()
    print("-AUC", roc_auc_score(y, pred_y))
    
print("Training performance\n=====")
evaluate_model(model, X_train, y_train)

print("Validation performance\n=====")
evaluate_model(model, X_valid, y_valid)


Training performance
=====
-Classification metrics
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       123
           1       1.00      1.00      1.00       112

    accuracy                           1.00       235
   macro avg       1.00      1.00      1.00       235
weighted avg       1.00      1.00      1.00       235


-Confusion matrix
 [[123   0]
 [  0 112]]

-AUC 1.0
Validation performance
=====
-Classification metrics
               precision    recall  f1-score   support

           0       0.84      0.78      0.81        41
           1       0.78      0.84      0.81        38

    accuracy                           0.81        79
   macro avg       0.81      0.81      0.81        79
weighted avg       0.81      0.81      0.81        79


-Confusion matrix
 [[32  9]
 [ 6 32]]

-AUC 0.8112965340179717


In [58]:
if hasattr(model, "feature_importances_"):
    imp = dict(zip(feat_names, model.feature_importances_))
    for k, v in imp.items():
        print(k,v)

LDH 0.30129760331873745
Age 0.13031097564719085
PaO2 0.22526386589729358
CRP 0.1608500374665725
WBC 0.10720210338971843
pH 0.07507541428048742


In [71]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, KFold

# l1 or l2
#logistic_pipe = Pipeline([
#    ("scaling", MinMaxScaler()),
#    ("fit", LogisticRegression(solver="liblinear"))])

#logistic_grid = {"scaling": [MinMaxScaler(), StandardScaler()],
#                 "fit__penalty": ["l1", "l2"],
#                 "fit__class_weight": [None, "balanced"]}

# none or 
logistic_pipe = Pipeline([
    ("scaling", MinMaxScaler()),
    ("fit", LogisticRegression(solver="lbfgs", penalty="none"))])

logistic_grid = {"scaling": [MinMaxScaler(), StandardScaler()],
                 "fit__class_weight": [None, "balanced"]}

searcher = GridSearchCV(
            estimator=logistic_pipe,
            param_grid=logistic_grid,
            cv=KFold(n_splits=5, shuffle=False),
            #scoring="neg_mean_absolute_error",
            verbose=1)
searcher.fit(X_train, y_train)
print(": grid-search best parameters", searcher.best_params_)
print(": grid-search best score", searcher.best_score_)
print()
evaluate_model(searcher.best_estimator_, X_train, y_train)
evaluate_model(searcher.best_estimator_, X_valid, y_valid)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
: grid-search best parameters {'fit__class_weight': 'balanced', 'scaling': MinMaxScaler()}
: grid-search best score 0.7404255319148936

-Classification metrics
               precision    recall  f1-score   support

           0       0.76      0.78      0.77       123
           1       0.75      0.73      0.74       112

    accuracy                           0.76       235
   macro avg       0.76      0.76      0.76       235
weighted avg       0.76      0.76      0.76       235


-Confusion matrix
 [[96 27]
 [30 82]]

-AUC 0.7563153310104529
-Classification metrics
               precision    recall  f1-score   support

           0       0.77      0.83      0.80        41
           1       0.80      0.74      0.77        38

    accuracy                           0.78        79
   macro avg       0.79      0.78      0.78        79
weighted avg       0.79      0.78      0.78        79


-Confusion matrix
 [[34  7]
 [10 28

In [73]:
rf_pipe = Pipeline([
    ("scaling", MinMaxScaler()),
    ("fit", RandomForestClassifier(n_estimators=100,
                                  # max_depth=5,
                                  # max_leaf_nodes=20,
                                  # min_impurity_decrease=.1
                                  random_state=42,
                                  ))
])
rf_grid = {"scaling": [MinMaxScaler(), StandardScaler()],
           "fit__n_estimators": [5, 10, 20, 100, 200],
           "fit__max_depth": [None, 5, 10, 20, 50],
           "fit__max_leaf_nodes": [None, 20, 50, 100],
           "fit__min_impurity_decrease": [0, 0.1, .5, 1]    }

searcher = GridSearchCV(
            estimator=rf_pipe,
            param_grid=rf_grid,
            cv=KFold(n_splits=5, shuffle=False),
            #scoring="neg_mean_absolute_error",
            verbose=1)
searcher.fit(X_train, y_train)
print(": grid-search best parameters", searcher.best_params_)
print(": grid-search best score", searcher.best_score_)
print()
evaluate_model(searcher.best_estimator_, X_train, y_train)
evaluate_model(searcher.best_estimator_, X_valid, y_valid)

Fitting 5 folds for each of 800 candidates, totalling 4000 fits
: grid-search best parameters {'fit__max_depth': None, 'fit__max_leaf_nodes': 20, 'fit__min_impurity_decrease': 0, 'fit__n_estimators': 5, 'scaling': StandardScaler()}
: grid-search best score 0.7361702127659574

-Classification metrics
               precision    recall  f1-score   support

           0       0.89      0.89      0.89       123
           1       0.88      0.88      0.88       112

    accuracy                           0.89       235
   macro avg       0.88      0.89      0.88       235
weighted avg       0.89      0.89      0.89       235


-Confusion matrix
 [[109  14]
 [ 13  99]]

-AUC 0.8850537166085947
-Classification metrics
               precision    recall  f1-score   support

           0       0.78      0.71      0.74        41
           1       0.71      0.79      0.75        38

    accuracy                           0.75        79
   macro avg       0.75      0.75      0.75        79
weight